// Generated by jextract

package lm.backend.ffm.llama_h;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class llama_h extends llama_h$shared {

    llama_h() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.libraryLookup("/opt/homebrew/opt/llama.cpp/lib/libllama.dylib", LIBRARY_ARENA)
            .or(SymbolLookup.loaderLookup())
            .or(Linker.nativeLinker().defaultLookup());

    /**
     * {@snippet lang=c :
     * typedef struct llama_memory_i *llama_memory_t
     * }
     */
    public static final AddressLayout llama_memory_t = llama_h.C_POINTER;
    /**
     * {@snippet lang=c :
     * typedef int32_t llama_pos
     * }
     */
    public static final OfInt llama_pos = llama_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef int32_t llama_token
     * }
     */
    public static final OfInt llama_token = llama_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef int32_t llama_seq_id
     * }
     */
    public static final OfInt llama_seq_id = llama_h.C_INT;

    private static class llama_model_default_params {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            llama_model_params.layout()    );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_model_default_params");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * struct llama_model_params llama_model_default_params()
     * }
     */
    public static FunctionDescriptor llama_model_default_params$descriptor() {
        return llama_model_default_params.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * struct llama_model_params llama_model_default_params()
     * }
     */
    public static MethodHandle llama_model_default_params$handle() {
        return llama_model_default_params.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * struct llama_model_params llama_model_default_params()
     * }
     */
    public static MemorySegment llama_model_default_params$address() {
        return llama_model_default_params.ADDR;
    }

    /**
     * {@snippet lang=c :
     * struct llama_model_params llama_model_default_params()
     * }
     */
    public static MemorySegment llama_model_default_params(SegmentAllocator allocator) {
        var mh$ = llama_model_default_params.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_model_default_params", allocator);
            }
            return (MemorySegment)mh$.invokeExact(allocator);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_context_default_params {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            llama_context_params.layout()    );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_context_default_params");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * struct llama_context_params llama_context_default_params()
     * }
     */
    public static FunctionDescriptor llama_context_default_params$descriptor() {
        return llama_context_default_params.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * struct llama_context_params llama_context_default_params()
     * }
     */
    public static MethodHandle llama_context_default_params$handle() {
        return llama_context_default_params.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * struct llama_context_params llama_context_default_params()
     * }
     */
    public static MemorySegment llama_context_default_params$address() {
        return llama_context_default_params.ADDR;
    }

    /**
     * {@snippet lang=c :
     * struct llama_context_params llama_context_default_params()
     * }
     */
    public static MemorySegment llama_context_default_params(SegmentAllocator allocator) {
        var mh$ = llama_context_default_params.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_context_default_params", allocator);
            }
            return (MemorySegment)mh$.invokeExact(allocator);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_sampler_chain_default_params {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            llama_sampler_chain_params.layout()    );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_sampler_chain_default_params");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * struct llama_sampler_chain_params llama_sampler_chain_default_params()
     * }
     */
    public static FunctionDescriptor llama_sampler_chain_default_params$descriptor() {
        return llama_sampler_chain_default_params.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * struct llama_sampler_chain_params llama_sampler_chain_default_params()
     * }
     */
    public static MethodHandle llama_sampler_chain_default_params$handle() {
        return llama_sampler_chain_default_params.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * struct llama_sampler_chain_params llama_sampler_chain_default_params()
     * }
     */
    public static MemorySegment llama_sampler_chain_default_params$address() {
        return llama_sampler_chain_default_params.ADDR;
    }

    /**
     * {@snippet lang=c :
     * struct llama_sampler_chain_params llama_sampler_chain_default_params()
     * }
     */
    public static MemorySegment llama_sampler_chain_default_params(SegmentAllocator allocator) {
        var mh$ = llama_sampler_chain_default_params.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_sampler_chain_default_params", allocator);
            }
            return (MemorySegment)mh$.invokeExact(allocator);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_backend_init {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(    );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_backend_init");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void llama_backend_init()
     * }
     */
    public static FunctionDescriptor llama_backend_init$descriptor() {
        return llama_backend_init.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void llama_backend_init()
     * }
     */
    public static MethodHandle llama_backend_init$handle() {
        return llama_backend_init.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void llama_backend_init()
     * }
     */
    public static MemorySegment llama_backend_init$address() {
        return llama_backend_init.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void llama_backend_init()
     * }
     */
    public static void llama_backend_init() {
        var mh$ = llama_backend_init.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_backend_init");
            }
            mh$.invokeExact();
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_backend_free {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(    );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_backend_free");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void llama_backend_free()
     * }
     */
    public static FunctionDescriptor llama_backend_free$descriptor() {
        return llama_backend_free.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void llama_backend_free()
     * }
     */
    public static MethodHandle llama_backend_free$handle() {
        return llama_backend_free.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void llama_backend_free()
     * }
     */
    public static MemorySegment llama_backend_free$address() {
        return llama_backend_free.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void llama_backend_free()
     * }
     */
    public static void llama_backend_free() {
        var mh$ = llama_backend_free.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_backend_free");
            }
            mh$.invokeExact();
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_model_load_from_file {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            llama_h.C_POINTER,
            llama_h.C_POINTER,
            llama_model_params.layout()
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_model_load_from_file");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * struct llama_model *llama_model_load_from_file(const char *path_model, struct llama_model_params params)
     * }
     */
    public static FunctionDescriptor llama_model_load_from_file$descriptor() {
        return llama_model_load_from_file.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * struct llama_model *llama_model_load_from_file(const char *path_model, struct llama_model_params params)
     * }
     */
    public static MethodHandle llama_model_load_from_file$handle() {
        return llama_model_load_from_file.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * struct llama_model *llama_model_load_from_file(const char *path_model, struct llama_model_params params)
     * }
     */
    public static MemorySegment llama_model_load_from_file$address() {
        return llama_model_load_from_file.ADDR;
    }

    /**
     * {@snippet lang=c :
     * struct llama_model *llama_model_load_from_file(const char *path_model, struct llama_model_params params)
     * }
     */
    public static MemorySegment llama_model_load_from_file(MemorySegment path_model, MemorySegment params) {
        var mh$ = llama_model_load_from_file.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_model_load_from_file", path_model, params);
            }
            return (MemorySegment)mh$.invokeExact(path_model, params);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_model_free {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            llama_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_model_free");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void llama_model_free(struct llama_model *model)
     * }
     */
    public static FunctionDescriptor llama_model_free$descriptor() {
        return llama_model_free.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void llama_model_free(struct llama_model *model)
     * }
     */
    public static MethodHandle llama_model_free$handle() {
        return llama_model_free.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void llama_model_free(struct llama_model *model)
     * }
     */
    public static MemorySegment llama_model_free$address() {
        return llama_model_free.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void llama_model_free(struct llama_model *model)
     * }
     */
    public static void llama_model_free(MemorySegment model) {
        var mh$ = llama_model_free.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_model_free", model);
            }
            mh$.invokeExact(model);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_new_context_with_model {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            llama_h.C_POINTER,
            llama_h.C_POINTER,
            llama_context_params.layout()
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_new_context_with_model");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * struct llama_context *llama_new_context_with_model(struct llama_model *model, struct llama_context_params params)
     * }
     */
    public static FunctionDescriptor llama_new_context_with_model$descriptor() {
        return llama_new_context_with_model.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * struct llama_context *llama_new_context_with_model(struct llama_model *model, struct llama_context_params params)
     * }
     */
    public static MethodHandle llama_new_context_with_model$handle() {
        return llama_new_context_with_model.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * struct llama_context *llama_new_context_with_model(struct llama_model *model, struct llama_context_params params)
     * }
     */
    public static MemorySegment llama_new_context_with_model$address() {
        return llama_new_context_with_model.ADDR;
    }

    /**
     * {@snippet lang=c :
     * struct llama_context *llama_new_context_with_model(struct llama_model *model, struct llama_context_params params)
     * }
     */
    public static MemorySegment llama_new_context_with_model(MemorySegment model, MemorySegment params) {
        var mh$ = llama_new_context_with_model.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_new_context_with_model", model, params);
            }
            return (MemorySegment)mh$.invokeExact(model, params);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_free {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            llama_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_free");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void llama_free(struct llama_context *ctx)
     * }
     */
    public static FunctionDescriptor llama_free$descriptor() {
        return llama_free.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void llama_free(struct llama_context *ctx)
     * }
     */
    public static MethodHandle llama_free$handle() {
        return llama_free.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void llama_free(struct llama_context *ctx)
     * }
     */
    public static MemorySegment llama_free$address() {
        return llama_free.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void llama_free(struct llama_context *ctx)
     * }
     */
    public static void llama_free(MemorySegment ctx) {
        var mh$ = llama_free.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_free", ctx);
            }
            mh$.invokeExact(ctx);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_n_ctx {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            llama_h.C_INT,
            llama_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_n_ctx");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * uint32_t llama_n_ctx(const struct llama_context *ctx)
     * }
     */
    public static FunctionDescriptor llama_n_ctx$descriptor() {
        return llama_n_ctx.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * uint32_t llama_n_ctx(const struct llama_context *ctx)
     * }
     */
    public static MethodHandle llama_n_ctx$handle() {
        return llama_n_ctx.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * uint32_t llama_n_ctx(const struct llama_context *ctx)
     * }
     */
    public static MemorySegment llama_n_ctx$address() {
        return llama_n_ctx.ADDR;
    }

    /**
     * {@snippet lang=c :
     * uint32_t llama_n_ctx(const struct llama_context *ctx)
     * }
     */
    public static int llama_n_ctx(MemorySegment ctx) {
        var mh$ = llama_n_ctx.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_n_ctx", ctx);
            }
            return (int)mh$.invokeExact(ctx);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_get_model {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            llama_h.C_POINTER,
            llama_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_get_model");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * const struct llama_model *llama_get_model(const struct llama_context *ctx)
     * }
     */
    public static FunctionDescriptor llama_get_model$descriptor() {
        return llama_get_model.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * const struct llama_model *llama_get_model(const struct llama_context *ctx)
     * }
     */
    public static MethodHandle llama_get_model$handle() {
        return llama_get_model.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * const struct llama_model *llama_get_model(const struct llama_context *ctx)
     * }
     */
    public static MemorySegment llama_get_model$address() {
        return llama_get_model.ADDR;
    }

    /**
     * {@snippet lang=c :
     * const struct llama_model *llama_get_model(const struct llama_context *ctx)
     * }
     */
    public static MemorySegment llama_get_model(MemorySegment ctx) {
        var mh$ = llama_get_model.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_get_model", ctx);
            }
            return (MemorySegment)mh$.invokeExact(ctx);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_get_memory {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            llama_h.C_POINTER,
            llama_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_get_memory");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * llama_memory_t llama_get_memory(const struct llama_context *ctx)
     * }
     */
    public static FunctionDescriptor llama_get_memory$descriptor() {
        return llama_get_memory.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * llama_memory_t llama_get_memory(const struct llama_context *ctx)
     * }
     */
    public static MethodHandle llama_get_memory$handle() {
        return llama_get_memory.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * llama_memory_t llama_get_memory(const struct llama_context *ctx)
     * }
     */
    public static MemorySegment llama_get_memory$address() {
        return llama_get_memory.ADDR;
    }

    /**
     * {@snippet lang=c :
     * llama_memory_t llama_get_memory(const struct llama_context *ctx)
     * }
     */
    public static MemorySegment llama_get_memory(MemorySegment ctx) {
        var mh$ = llama_get_memory.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_get_memory", ctx);
            }
            return (MemorySegment)mh$.invokeExact(ctx);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_model_get_vocab {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            llama_h.C_POINTER,
            llama_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_model_get_vocab");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * const struct llama_vocab *llama_model_get_vocab(const struct llama_model *model)
     * }
     */
    public static FunctionDescriptor llama_model_get_vocab$descriptor() {
        return llama_model_get_vocab.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * const struct llama_vocab *llama_model_get_vocab(const struct llama_model *model)
     * }
     */
    public static MethodHandle llama_model_get_vocab$handle() {
        return llama_model_get_vocab.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * const struct llama_vocab *llama_model_get_vocab(const struct llama_model *model)
     * }
     */
    public static MemorySegment llama_model_get_vocab$address() {
        return llama_model_get_vocab.ADDR;
    }

    /**
     * {@snippet lang=c :
     * const struct llama_vocab *llama_model_get_vocab(const struct llama_model *model)
     * }
     */
    public static MemorySegment llama_model_get_vocab(MemorySegment model) {
        var mh$ = llama_model_get_vocab.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_model_get_vocab", model);
            }
            return (MemorySegment)mh$.invokeExact(model);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_model_n_ctx_train {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            llama_h.C_INT,
            llama_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_model_n_ctx_train");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t llama_model_n_ctx_train(const struct llama_model *model)
     * }
     */
    public static FunctionDescriptor llama_model_n_ctx_train$descriptor() {
        return llama_model_n_ctx_train.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t llama_model_n_ctx_train(const struct llama_model *model)
     * }
     */
    public static MethodHandle llama_model_n_ctx_train$handle() {
        return llama_model_n_ctx_train.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t llama_model_n_ctx_train(const struct llama_model *model)
     * }
     */
    public static MemorySegment llama_model_n_ctx_train$address() {
        return llama_model_n_ctx_train.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t llama_model_n_ctx_train(const struct llama_model *model)
     * }
     */
    public static int llama_model_n_ctx_train(MemorySegment model) {
        var mh$ = llama_model_n_ctx_train.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_model_n_ctx_train", model);
            }
            return (int)mh$.invokeExact(model);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_model_n_embd {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            llama_h.C_INT,
            llama_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_model_n_embd");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t llama_model_n_embd(const struct llama_model *model)
     * }
     */
    public static FunctionDescriptor llama_model_n_embd$descriptor() {
        return llama_model_n_embd.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t llama_model_n_embd(const struct llama_model *model)
     * }
     */
    public static MethodHandle llama_model_n_embd$handle() {
        return llama_model_n_embd.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t llama_model_n_embd(const struct llama_model *model)
     * }
     */
    public static MemorySegment llama_model_n_embd$address() {
        return llama_model_n_embd.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t llama_model_n_embd(const struct llama_model *model)
     * }
     */
    public static int llama_model_n_embd(MemorySegment model) {
        var mh$ = llama_model_n_embd.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_model_n_embd", model);
            }
            return (int)mh$.invokeExact(model);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_vocab_n_tokens {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            llama_h.C_INT,
            llama_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_vocab_n_tokens");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t llama_vocab_n_tokens(const struct llama_vocab *vocab)
     * }
     */
    public static FunctionDescriptor llama_vocab_n_tokens$descriptor() {
        return llama_vocab_n_tokens.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t llama_vocab_n_tokens(const struct llama_vocab *vocab)
     * }
     */
    public static MethodHandle llama_vocab_n_tokens$handle() {
        return llama_vocab_n_tokens.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t llama_vocab_n_tokens(const struct llama_vocab *vocab)
     * }
     */
    public static MemorySegment llama_vocab_n_tokens$address() {
        return llama_vocab_n_tokens.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t llama_vocab_n_tokens(const struct llama_vocab *vocab)
     * }
     */
    public static int llama_vocab_n_tokens(MemorySegment vocab) {
        var mh$ = llama_vocab_n_tokens.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_vocab_n_tokens", vocab);
            }
            return (int)mh$.invokeExact(vocab);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_memory_clear {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            llama_h.C_POINTER,
            llama_h.C_BOOL
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_memory_clear");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void llama_memory_clear(llama_memory_t mem, _Bool data)
     * }
     */
    public static FunctionDescriptor llama_memory_clear$descriptor() {
        return llama_memory_clear.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void llama_memory_clear(llama_memory_t mem, _Bool data)
     * }
     */
    public static MethodHandle llama_memory_clear$handle() {
        return llama_memory_clear.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void llama_memory_clear(llama_memory_t mem, _Bool data)
     * }
     */
    public static MemorySegment llama_memory_clear$address() {
        return llama_memory_clear.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void llama_memory_clear(llama_memory_t mem, _Bool data)
     * }
     */
    public static void llama_memory_clear(MemorySegment mem, boolean data) {
        var mh$ = llama_memory_clear.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_memory_clear", mem, data);
            }
            mh$.invokeExact(mem, data);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_memory_seq_rm {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            llama_h.C_BOOL,
            llama_h.C_POINTER,
            llama_h.C_INT,
            llama_h.C_INT,
            llama_h.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_memory_seq_rm");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * _Bool llama_memory_seq_rm(llama_memory_t mem, llama_seq_id seq_id, llama_pos p0, llama_pos p1)
     * }
     */
    public static FunctionDescriptor llama_memory_seq_rm$descriptor() {
        return llama_memory_seq_rm.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * _Bool llama_memory_seq_rm(llama_memory_t mem, llama_seq_id seq_id, llama_pos p0, llama_pos p1)
     * }
     */
    public static MethodHandle llama_memory_seq_rm$handle() {
        return llama_memory_seq_rm.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * _Bool llama_memory_seq_rm(llama_memory_t mem, llama_seq_id seq_id, llama_pos p0, llama_pos p1)
     * }
     */
    public static MemorySegment llama_memory_seq_rm$address() {
        return llama_memory_seq_rm.ADDR;
    }

    /**
     * {@snippet lang=c :
     * _Bool llama_memory_seq_rm(llama_memory_t mem, llama_seq_id seq_id, llama_pos p0, llama_pos p1)
     * }
     */
    public static boolean llama_memory_seq_rm(MemorySegment mem, int seq_id, int p0, int p1) {
        var mh$ = llama_memory_seq_rm.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_memory_seq_rm", mem, seq_id, p0, p1);
            }
            return (boolean)mh$.invokeExact(mem, seq_id, p0, p1);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_batch_get_one {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            llama_batch.layout(),
            llama_h.C_POINTER,
            llama_h.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_batch_get_one");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * struct llama_batch llama_batch_get_one(llama_token *tokens, int32_t n_tokens)
     * }
     */
    public static FunctionDescriptor llama_batch_get_one$descriptor() {
        return llama_batch_get_one.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * struct llama_batch llama_batch_get_one(llama_token *tokens, int32_t n_tokens)
     * }
     */
    public static MethodHandle llama_batch_get_one$handle() {
        return llama_batch_get_one.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * struct llama_batch llama_batch_get_one(llama_token *tokens, int32_t n_tokens)
     * }
     */
    public static MemorySegment llama_batch_get_one$address() {
        return llama_batch_get_one.ADDR;
    }

    /**
     * {@snippet lang=c :
     * struct llama_batch llama_batch_get_one(llama_token *tokens, int32_t n_tokens)
     * }
     */
    public static MemorySegment llama_batch_get_one(SegmentAllocator allocator, MemorySegment tokens, int n_tokens) {
        var mh$ = llama_batch_get_one.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_batch_get_one", allocator, tokens, n_tokens);
            }
            return (MemorySegment)mh$.invokeExact(allocator, tokens, n_tokens);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_batch_init {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            llama_batch.layout(),
            llama_h.C_INT,
            llama_h.C_INT,
            llama_h.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_batch_init");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * struct llama_batch llama_batch_init(int32_t n_tokens, int32_t embd, int32_t n_seq_max)
     * }
     */
    public static FunctionDescriptor llama_batch_init$descriptor() {
        return llama_batch_init.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * struct llama_batch llama_batch_init(int32_t n_tokens, int32_t embd, int32_t n_seq_max)
     * }
     */
    public static MethodHandle llama_batch_init$handle() {
        return llama_batch_init.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * struct llama_batch llama_batch_init(int32_t n_tokens, int32_t embd, int32_t n_seq_max)
     * }
     */
    public static MemorySegment llama_batch_init$address() {
        return llama_batch_init.ADDR;
    }

    /**
     * {@snippet lang=c :
     * struct llama_batch llama_batch_init(int32_t n_tokens, int32_t embd, int32_t n_seq_max)
     * }
     */
    public static MemorySegment llama_batch_init(SegmentAllocator allocator, int n_tokens, int embd, int n_seq_max) {
        var mh$ = llama_batch_init.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_batch_init", allocator, n_tokens, embd, n_seq_max);
            }
            return (MemorySegment)mh$.invokeExact(allocator, n_tokens, embd, n_seq_max);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_batch_free {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            llama_batch.layout()
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_batch_free");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void llama_batch_free(struct llama_batch batch)
     * }
     */
    public static FunctionDescriptor llama_batch_free$descriptor() {
        return llama_batch_free.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void llama_batch_free(struct llama_batch batch)
     * }
     */
    public static MethodHandle llama_batch_free$handle() {
        return llama_batch_free.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void llama_batch_free(struct llama_batch batch)
     * }
     */
    public static MemorySegment llama_batch_free$address() {
        return llama_batch_free.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void llama_batch_free(struct llama_batch batch)
     * }
     */
    public static void llama_batch_free(MemorySegment batch) {
        var mh$ = llama_batch_free.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_batch_free", batch);
            }
            mh$.invokeExact(batch);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_decode {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            llama_h.C_INT,
            llama_h.C_POINTER,
            llama_batch.layout()
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_decode");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t llama_decode(struct llama_context *ctx, struct llama_batch batch)
     * }
     */
    public static FunctionDescriptor llama_decode$descriptor() {
        return llama_decode.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t llama_decode(struct llama_context *ctx, struct llama_batch batch)
     * }
     */
    public static MethodHandle llama_decode$handle() {
        return llama_decode.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t llama_decode(struct llama_context *ctx, struct llama_batch batch)
     * }
     */
    public static MemorySegment llama_decode$address() {
        return llama_decode.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t llama_decode(struct llama_context *ctx, struct llama_batch batch)
     * }
     */
    public static int llama_decode(MemorySegment ctx, MemorySegment batch) {
        var mh$ = llama_decode.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_decode", ctx, batch);
            }
            return (int)mh$.invokeExact(ctx, batch);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_set_n_threads {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            llama_h.C_POINTER,
            llama_h.C_INT,
            llama_h.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_set_n_threads");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void llama_set_n_threads(struct llama_context *ctx, int32_t n_threads, int32_t n_threads_batch)
     * }
     */
    public static FunctionDescriptor llama_set_n_threads$descriptor() {
        return llama_set_n_threads.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void llama_set_n_threads(struct llama_context *ctx, int32_t n_threads, int32_t n_threads_batch)
     * }
     */
    public static MethodHandle llama_set_n_threads$handle() {
        return llama_set_n_threads.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void llama_set_n_threads(struct llama_context *ctx, int32_t n_threads, int32_t n_threads_batch)
     * }
     */
    public static MemorySegment llama_set_n_threads$address() {
        return llama_set_n_threads.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void llama_set_n_threads(struct llama_context *ctx, int32_t n_threads, int32_t n_threads_batch)
     * }
     */
    public static void llama_set_n_threads(MemorySegment ctx, int n_threads, int n_threads_batch) {
        var mh$ = llama_set_n_threads.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_set_n_threads", ctx, n_threads, n_threads_batch);
            }
            mh$.invokeExact(ctx, n_threads, n_threads_batch);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_get_logits {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            llama_h.C_POINTER,
            llama_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_get_logits");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * float *llama_get_logits(struct llama_context *ctx)
     * }
     */
    public static FunctionDescriptor llama_get_logits$descriptor() {
        return llama_get_logits.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * float *llama_get_logits(struct llama_context *ctx)
     * }
     */
    public static MethodHandle llama_get_logits$handle() {
        return llama_get_logits.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * float *llama_get_logits(struct llama_context *ctx)
     * }
     */
    public static MemorySegment llama_get_logits$address() {
        return llama_get_logits.ADDR;
    }

    /**
     * {@snippet lang=c :
     * float *llama_get_logits(struct llama_context *ctx)
     * }
     */
    public static MemorySegment llama_get_logits(MemorySegment ctx) {
        var mh$ = llama_get_logits.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_get_logits", ctx);
            }
            return (MemorySegment)mh$.invokeExact(ctx);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_get_logits_ith {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            llama_h.C_POINTER,
            llama_h.C_POINTER,
            llama_h.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_get_logits_ith");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * float *llama_get_logits_ith(struct llama_context *ctx, int32_t i)
     * }
     */
    public static FunctionDescriptor llama_get_logits_ith$descriptor() {
        return llama_get_logits_ith.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * float *llama_get_logits_ith(struct llama_context *ctx, int32_t i)
     * }
     */
    public static MethodHandle llama_get_logits_ith$handle() {
        return llama_get_logits_ith.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * float *llama_get_logits_ith(struct llama_context *ctx, int32_t i)
     * }
     */
    public static MemorySegment llama_get_logits_ith$address() {
        return llama_get_logits_ith.ADDR;
    }

    /**
     * {@snippet lang=c :
     * float *llama_get_logits_ith(struct llama_context *ctx, int32_t i)
     * }
     */
    public static MemorySegment llama_get_logits_ith(MemorySegment ctx, int i) {
        var mh$ = llama_get_logits_ith.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_get_logits_ith", ctx, i);
            }
            return (MemorySegment)mh$.invokeExact(ctx, i);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_vocab_get_text {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            llama_h.C_POINTER,
            llama_h.C_POINTER,
            llama_h.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_vocab_get_text");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * const char *llama_vocab_get_text(const struct llama_vocab *vocab, llama_token token)
     * }
     */
    public static FunctionDescriptor llama_vocab_get_text$descriptor() {
        return llama_vocab_get_text.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * const char *llama_vocab_get_text(const struct llama_vocab *vocab, llama_token token)
     * }
     */
    public static MethodHandle llama_vocab_get_text$handle() {
        return llama_vocab_get_text.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * const char *llama_vocab_get_text(const struct llama_vocab *vocab, llama_token token)
     * }
     */
    public static MemorySegment llama_vocab_get_text$address() {
        return llama_vocab_get_text.ADDR;
    }

    /**
     * {@snippet lang=c :
     * const char *llama_vocab_get_text(const struct llama_vocab *vocab, llama_token token)
     * }
     */
    public static MemorySegment llama_vocab_get_text(MemorySegment vocab, int token) {
        var mh$ = llama_vocab_get_text.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_vocab_get_text", vocab, token);
            }
            return (MemorySegment)mh$.invokeExact(vocab, token);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_vocab_is_eog {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            llama_h.C_BOOL,
            llama_h.C_POINTER,
            llama_h.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_vocab_is_eog");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * _Bool llama_vocab_is_eog(const struct llama_vocab *vocab, llama_token token)
     * }
     */
    public static FunctionDescriptor llama_vocab_is_eog$descriptor() {
        return llama_vocab_is_eog.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * _Bool llama_vocab_is_eog(const struct llama_vocab *vocab, llama_token token)
     * }
     */
    public static MethodHandle llama_vocab_is_eog$handle() {
        return llama_vocab_is_eog.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * _Bool llama_vocab_is_eog(const struct llama_vocab *vocab, llama_token token)
     * }
     */
    public static MemorySegment llama_vocab_is_eog$address() {
        return llama_vocab_is_eog.ADDR;
    }

    /**
     * {@snippet lang=c :
     * _Bool llama_vocab_is_eog(const struct llama_vocab *vocab, llama_token token)
     * }
     */
    public static boolean llama_vocab_is_eog(MemorySegment vocab, int token) {
        var mh$ = llama_vocab_is_eog.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_vocab_is_eog", vocab, token);
            }
            return (boolean)mh$.invokeExact(vocab, token);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_vocab_bos {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            llama_h.C_INT,
            llama_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_vocab_bos");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * llama_token llama_vocab_bos(const struct llama_vocab *vocab)
     * }
     */
    public static FunctionDescriptor llama_vocab_bos$descriptor() {
        return llama_vocab_bos.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * llama_token llama_vocab_bos(const struct llama_vocab *vocab)
     * }
     */
    public static MethodHandle llama_vocab_bos$handle() {
        return llama_vocab_bos.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * llama_token llama_vocab_bos(const struct llama_vocab *vocab)
     * }
     */
    public static MemorySegment llama_vocab_bos$address() {
        return llama_vocab_bos.ADDR;
    }

    /**
     * {@snippet lang=c :
     * llama_token llama_vocab_bos(const struct llama_vocab *vocab)
     * }
     */
    public static int llama_vocab_bos(MemorySegment vocab) {
        var mh$ = llama_vocab_bos.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_vocab_bos", vocab);
            }
            return (int)mh$.invokeExact(vocab);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_vocab_eos {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            llama_h.C_INT,
            llama_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_vocab_eos");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * llama_token llama_vocab_eos(const struct llama_vocab *vocab)
     * }
     */
    public static FunctionDescriptor llama_vocab_eos$descriptor() {
        return llama_vocab_eos.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * llama_token llama_vocab_eos(const struct llama_vocab *vocab)
     * }
     */
    public static MethodHandle llama_vocab_eos$handle() {
        return llama_vocab_eos.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * llama_token llama_vocab_eos(const struct llama_vocab *vocab)
     * }
     */
    public static MemorySegment llama_vocab_eos$address() {
        return llama_vocab_eos.ADDR;
    }

    /**
     * {@snippet lang=c :
     * llama_token llama_vocab_eos(const struct llama_vocab *vocab)
     * }
     */
    public static int llama_vocab_eos(MemorySegment vocab) {
        var mh$ = llama_vocab_eos.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_vocab_eos", vocab);
            }
            return (int)mh$.invokeExact(vocab);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_vocab_get_add_bos {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            llama_h.C_BOOL,
            llama_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_vocab_get_add_bos");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * _Bool llama_vocab_get_add_bos(const struct llama_vocab *vocab)
     * }
     */
    public static FunctionDescriptor llama_vocab_get_add_bos$descriptor() {
        return llama_vocab_get_add_bos.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * _Bool llama_vocab_get_add_bos(const struct llama_vocab *vocab)
     * }
     */
    public static MethodHandle llama_vocab_get_add_bos$handle() {
        return llama_vocab_get_add_bos.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * _Bool llama_vocab_get_add_bos(const struct llama_vocab *vocab)
     * }
     */
    public static MemorySegment llama_vocab_get_add_bos$address() {
        return llama_vocab_get_add_bos.ADDR;
    }

    /**
     * {@snippet lang=c :
     * _Bool llama_vocab_get_add_bos(const struct llama_vocab *vocab)
     * }
     */
    public static boolean llama_vocab_get_add_bos(MemorySegment vocab) {
        var mh$ = llama_vocab_get_add_bos.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_vocab_get_add_bos", vocab);
            }
            return (boolean)mh$.invokeExact(vocab);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_vocab_get_add_eos {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            llama_h.C_BOOL,
            llama_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_vocab_get_add_eos");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * _Bool llama_vocab_get_add_eos(const struct llama_vocab *vocab)
     * }
     */
    public static FunctionDescriptor llama_vocab_get_add_eos$descriptor() {
        return llama_vocab_get_add_eos.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * _Bool llama_vocab_get_add_eos(const struct llama_vocab *vocab)
     * }
     */
    public static MethodHandle llama_vocab_get_add_eos$handle() {
        return llama_vocab_get_add_eos.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * _Bool llama_vocab_get_add_eos(const struct llama_vocab *vocab)
     * }
     */
    public static MemorySegment llama_vocab_get_add_eos$address() {
        return llama_vocab_get_add_eos.ADDR;
    }

    /**
     * {@snippet lang=c :
     * _Bool llama_vocab_get_add_eos(const struct llama_vocab *vocab)
     * }
     */
    public static boolean llama_vocab_get_add_eos(MemorySegment vocab) {
        var mh$ = llama_vocab_get_add_eos.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_vocab_get_add_eos", vocab);
            }
            return (boolean)mh$.invokeExact(vocab);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_tokenize {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            llama_h.C_INT,
            llama_h.C_POINTER,
            llama_h.C_POINTER,
            llama_h.C_INT,
            llama_h.C_POINTER,
            llama_h.C_INT,
            llama_h.C_BOOL,
            llama_h.C_BOOL
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_tokenize");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t llama_tokenize(const struct llama_vocab *vocab, const char *text, int32_t text_len, llama_token *tokens, int32_t n_tokens_max, _Bool add_special, _Bool parse_special)
     * }
     */
    public static FunctionDescriptor llama_tokenize$descriptor() {
        return llama_tokenize.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t llama_tokenize(const struct llama_vocab *vocab, const char *text, int32_t text_len, llama_token *tokens, int32_t n_tokens_max, _Bool add_special, _Bool parse_special)
     * }
     */
    public static MethodHandle llama_tokenize$handle() {
        return llama_tokenize.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t llama_tokenize(const struct llama_vocab *vocab, const char *text, int32_t text_len, llama_token *tokens, int32_t n_tokens_max, _Bool add_special, _Bool parse_special)
     * }
     */
    public static MemorySegment llama_tokenize$address() {
        return llama_tokenize.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t llama_tokenize(const struct llama_vocab *vocab, const char *text, int32_t text_len, llama_token *tokens, int32_t n_tokens_max, _Bool add_special, _Bool parse_special)
     * }
     */
    public static int llama_tokenize(MemorySegment vocab, MemorySegment text, int text_len, MemorySegment tokens, int n_tokens_max, boolean add_special, boolean parse_special) {
        var mh$ = llama_tokenize.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_tokenize", vocab, text, text_len, tokens, n_tokens_max, add_special, parse_special);
            }
            return (int)mh$.invokeExact(vocab, text, text_len, tokens, n_tokens_max, add_special, parse_special);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_token_to_piece {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            llama_h.C_INT,
            llama_h.C_POINTER,
            llama_h.C_INT,
            llama_h.C_POINTER,
            llama_h.C_INT,
            llama_h.C_INT,
            llama_h.C_BOOL
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_token_to_piece");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t llama_token_to_piece(const struct llama_vocab *vocab, llama_token token, char *buf, int32_t length, int32_t lstrip, _Bool special)
     * }
     */
    public static FunctionDescriptor llama_token_to_piece$descriptor() {
        return llama_token_to_piece.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t llama_token_to_piece(const struct llama_vocab *vocab, llama_token token, char *buf, int32_t length, int32_t lstrip, _Bool special)
     * }
     */
    public static MethodHandle llama_token_to_piece$handle() {
        return llama_token_to_piece.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t llama_token_to_piece(const struct llama_vocab *vocab, llama_token token, char *buf, int32_t length, int32_t lstrip, _Bool special)
     * }
     */
    public static MemorySegment llama_token_to_piece$address() {
        return llama_token_to_piece.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t llama_token_to_piece(const struct llama_vocab *vocab, llama_token token, char *buf, int32_t length, int32_t lstrip, _Bool special)
     * }
     */
    public static int llama_token_to_piece(MemorySegment vocab, int token, MemorySegment buf, int length, int lstrip, boolean special) {
        var mh$ = llama_token_to_piece.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_token_to_piece", vocab, token, buf, length, lstrip, special);
            }
            return (int)mh$.invokeExact(vocab, token, buf, length, lstrip, special);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_detokenize {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            llama_h.C_INT,
            llama_h.C_POINTER,
            llama_h.C_POINTER,
            llama_h.C_INT,
            llama_h.C_POINTER,
            llama_h.C_INT,
            llama_h.C_BOOL,
            llama_h.C_BOOL
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_detokenize");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t llama_detokenize(const struct llama_vocab *vocab, const llama_token *tokens, int32_t n_tokens, char *text, int32_t text_len_max, _Bool remove_special, _Bool unparse_special)
     * }
     */
    public static FunctionDescriptor llama_detokenize$descriptor() {
        return llama_detokenize.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t llama_detokenize(const struct llama_vocab *vocab, const llama_token *tokens, int32_t n_tokens, char *text, int32_t text_len_max, _Bool remove_special, _Bool unparse_special)
     * }
     */
    public static MethodHandle llama_detokenize$handle() {
        return llama_detokenize.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t llama_detokenize(const struct llama_vocab *vocab, const llama_token *tokens, int32_t n_tokens, char *text, int32_t text_len_max, _Bool remove_special, _Bool unparse_special)
     * }
     */
    public static MemorySegment llama_detokenize$address() {
        return llama_detokenize.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t llama_detokenize(const struct llama_vocab *vocab, const llama_token *tokens, int32_t n_tokens, char *text, int32_t text_len_max, _Bool remove_special, _Bool unparse_special)
     * }
     */
    public static int llama_detokenize(MemorySegment vocab, MemorySegment tokens, int n_tokens, MemorySegment text, int text_len_max, boolean remove_special, boolean unparse_special) {
        var mh$ = llama_detokenize.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_detokenize", vocab, tokens, n_tokens, text, text_len_max, remove_special, unparse_special);
            }
            return (int)mh$.invokeExact(vocab, tokens, n_tokens, text, text_len_max, remove_special, unparse_special);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_chat_apply_template {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            llama_h.C_INT,
            llama_h.C_POINTER,
            llama_h.C_POINTER,
            llama_h.C_LONG,
            llama_h.C_BOOL,
            llama_h.C_POINTER,
            llama_h.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_chat_apply_template");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t llama_chat_apply_template(const char *tmpl, const struct llama_chat_message *chat, size_t n_msg, _Bool add_ass, char *buf, int32_t length)
     * }
     */
    public static FunctionDescriptor llama_chat_apply_template$descriptor() {
        return llama_chat_apply_template.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t llama_chat_apply_template(const char *tmpl, const struct llama_chat_message *chat, size_t n_msg, _Bool add_ass, char *buf, int32_t length)
     * }
     */
    public static MethodHandle llama_chat_apply_template$handle() {
        return llama_chat_apply_template.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t llama_chat_apply_template(const char *tmpl, const struct llama_chat_message *chat, size_t n_msg, _Bool add_ass, char *buf, int32_t length)
     * }
     */
    public static MemorySegment llama_chat_apply_template$address() {
        return llama_chat_apply_template.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t llama_chat_apply_template(const char *tmpl, const struct llama_chat_message *chat, size_t n_msg, _Bool add_ass, char *buf, int32_t length)
     * }
     */
    public static int llama_chat_apply_template(MemorySegment tmpl, MemorySegment chat, long n_msg, boolean add_ass, MemorySegment buf, int length) {
        var mh$ = llama_chat_apply_template.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_chat_apply_template", tmpl, chat, n_msg, add_ass, buf, length);
            }
            return (int)mh$.invokeExact(tmpl, chat, n_msg, add_ass, buf, length);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_sampler_accept {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            llama_h.C_POINTER,
            llama_h.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_sampler_accept");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void llama_sampler_accept(struct llama_sampler *smpl, llama_token token)
     * }
     */
    public static FunctionDescriptor llama_sampler_accept$descriptor() {
        return llama_sampler_accept.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void llama_sampler_accept(struct llama_sampler *smpl, llama_token token)
     * }
     */
    public static MethodHandle llama_sampler_accept$handle() {
        return llama_sampler_accept.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void llama_sampler_accept(struct llama_sampler *smpl, llama_token token)
     * }
     */
    public static MemorySegment llama_sampler_accept$address() {
        return llama_sampler_accept.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void llama_sampler_accept(struct llama_sampler *smpl, llama_token token)
     * }
     */
    public static void llama_sampler_accept(MemorySegment smpl, int token) {
        var mh$ = llama_sampler_accept.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_sampler_accept", smpl, token);
            }
            mh$.invokeExact(smpl, token);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_sampler_reset {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            llama_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_sampler_reset");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void llama_sampler_reset(struct llama_sampler *smpl)
     * }
     */
    public static FunctionDescriptor llama_sampler_reset$descriptor() {
        return llama_sampler_reset.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void llama_sampler_reset(struct llama_sampler *smpl)
     * }
     */
    public static MethodHandle llama_sampler_reset$handle() {
        return llama_sampler_reset.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void llama_sampler_reset(struct llama_sampler *smpl)
     * }
     */
    public static MemorySegment llama_sampler_reset$address() {
        return llama_sampler_reset.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void llama_sampler_reset(struct llama_sampler *smpl)
     * }
     */
    public static void llama_sampler_reset(MemorySegment smpl) {
        var mh$ = llama_sampler_reset.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_sampler_reset", smpl);
            }
            mh$.invokeExact(smpl);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_sampler_free {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            llama_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_sampler_free");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void llama_sampler_free(struct llama_sampler *smpl)
     * }
     */
    public static FunctionDescriptor llama_sampler_free$descriptor() {
        return llama_sampler_free.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void llama_sampler_free(struct llama_sampler *smpl)
     * }
     */
    public static MethodHandle llama_sampler_free$handle() {
        return llama_sampler_free.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void llama_sampler_free(struct llama_sampler *smpl)
     * }
     */
    public static MemorySegment llama_sampler_free$address() {
        return llama_sampler_free.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void llama_sampler_free(struct llama_sampler *smpl)
     * }
     */
    public static void llama_sampler_free(MemorySegment smpl) {
        var mh$ = llama_sampler_free.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_sampler_free", smpl);
            }
            mh$.invokeExact(smpl);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_sampler_chain_init {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            llama_h.C_POINTER,
            llama_sampler_chain_params.layout()
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_sampler_chain_init");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * struct llama_sampler *llama_sampler_chain_init(struct llama_sampler_chain_params params)
     * }
     */
    public static FunctionDescriptor llama_sampler_chain_init$descriptor() {
        return llama_sampler_chain_init.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * struct llama_sampler *llama_sampler_chain_init(struct llama_sampler_chain_params params)
     * }
     */
    public static MethodHandle llama_sampler_chain_init$handle() {
        return llama_sampler_chain_init.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * struct llama_sampler *llama_sampler_chain_init(struct llama_sampler_chain_params params)
     * }
     */
    public static MemorySegment llama_sampler_chain_init$address() {
        return llama_sampler_chain_init.ADDR;
    }

    /**
     * {@snippet lang=c :
     * struct llama_sampler *llama_sampler_chain_init(struct llama_sampler_chain_params params)
     * }
     */
    public static MemorySegment llama_sampler_chain_init(MemorySegment params) {
        var mh$ = llama_sampler_chain_init.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_sampler_chain_init", params);
            }
            return (MemorySegment)mh$.invokeExact(params);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_sampler_chain_add {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            llama_h.C_POINTER,
            llama_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_sampler_chain_add");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void llama_sampler_chain_add(struct llama_sampler *chain, struct llama_sampler *smpl)
     * }
     */
    public static FunctionDescriptor llama_sampler_chain_add$descriptor() {
        return llama_sampler_chain_add.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void llama_sampler_chain_add(struct llama_sampler *chain, struct llama_sampler *smpl)
     * }
     */
    public static MethodHandle llama_sampler_chain_add$handle() {
        return llama_sampler_chain_add.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void llama_sampler_chain_add(struct llama_sampler *chain, struct llama_sampler *smpl)
     * }
     */
    public static MemorySegment llama_sampler_chain_add$address() {
        return llama_sampler_chain_add.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void llama_sampler_chain_add(struct llama_sampler *chain, struct llama_sampler *smpl)
     * }
     */
    public static void llama_sampler_chain_add(MemorySegment chain, MemorySegment smpl) {
        var mh$ = llama_sampler_chain_add.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_sampler_chain_add", chain, smpl);
            }
            mh$.invokeExact(chain, smpl);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_sampler_init_greedy {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            llama_h.C_POINTER    );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_sampler_init_greedy");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * struct llama_sampler *llama_sampler_init_greedy()
     * }
     */
    public static FunctionDescriptor llama_sampler_init_greedy$descriptor() {
        return llama_sampler_init_greedy.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * struct llama_sampler *llama_sampler_init_greedy()
     * }
     */
    public static MethodHandle llama_sampler_init_greedy$handle() {
        return llama_sampler_init_greedy.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * struct llama_sampler *llama_sampler_init_greedy()
     * }
     */
    public static MemorySegment llama_sampler_init_greedy$address() {
        return llama_sampler_init_greedy.ADDR;
    }

    /**
     * {@snippet lang=c :
     * struct llama_sampler *llama_sampler_init_greedy()
     * }
     */
    public static MemorySegment llama_sampler_init_greedy() {
        var mh$ = llama_sampler_init_greedy.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_sampler_init_greedy");
            }
            return (MemorySegment)mh$.invokeExact();
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_sampler_init_dist {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            llama_h.C_POINTER,
            llama_h.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_sampler_init_dist");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * struct llama_sampler *llama_sampler_init_dist(uint32_t seed)
     * }
     */
    public static FunctionDescriptor llama_sampler_init_dist$descriptor() {
        return llama_sampler_init_dist.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * struct llama_sampler *llama_sampler_init_dist(uint32_t seed)
     * }
     */
    public static MethodHandle llama_sampler_init_dist$handle() {
        return llama_sampler_init_dist.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * struct llama_sampler *llama_sampler_init_dist(uint32_t seed)
     * }
     */
    public static MemorySegment llama_sampler_init_dist$address() {
        return llama_sampler_init_dist.ADDR;
    }

    /**
     * {@snippet lang=c :
     * struct llama_sampler *llama_sampler_init_dist(uint32_t seed)
     * }
     */
    public static MemorySegment llama_sampler_init_dist(int seed) {
        var mh$ = llama_sampler_init_dist.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_sampler_init_dist", seed);
            }
            return (MemorySegment)mh$.invokeExact(seed);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_sampler_init_top_k {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            llama_h.C_POINTER,
            llama_h.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_sampler_init_top_k");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * struct llama_sampler *llama_sampler_init_top_k(int32_t k)
     * }
     */
    public static FunctionDescriptor llama_sampler_init_top_k$descriptor() {
        return llama_sampler_init_top_k.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * struct llama_sampler *llama_sampler_init_top_k(int32_t k)
     * }
     */
    public static MethodHandle llama_sampler_init_top_k$handle() {
        return llama_sampler_init_top_k.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * struct llama_sampler *llama_sampler_init_top_k(int32_t k)
     * }
     */
    public static MemorySegment llama_sampler_init_top_k$address() {
        return llama_sampler_init_top_k.ADDR;
    }

    /**
     * {@snippet lang=c :
     * struct llama_sampler *llama_sampler_init_top_k(int32_t k)
     * }
     */
    public static MemorySegment llama_sampler_init_top_k(int k) {
        var mh$ = llama_sampler_init_top_k.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_sampler_init_top_k", k);
            }
            return (MemorySegment)mh$.invokeExact(k);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_sampler_init_top_p {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            llama_h.C_POINTER,
            llama_h.C_FLOAT,
            llama_h.C_LONG
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_sampler_init_top_p");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * struct llama_sampler *llama_sampler_init_top_p(float p, size_t min_keep)
     * }
     */
    public static FunctionDescriptor llama_sampler_init_top_p$descriptor() {
        return llama_sampler_init_top_p.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * struct llama_sampler *llama_sampler_init_top_p(float p, size_t min_keep)
     * }
     */
    public static MethodHandle llama_sampler_init_top_p$handle() {
        return llama_sampler_init_top_p.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * struct llama_sampler *llama_sampler_init_top_p(float p, size_t min_keep)
     * }
     */
    public static MemorySegment llama_sampler_init_top_p$address() {
        return llama_sampler_init_top_p.ADDR;
    }

    /**
     * {@snippet lang=c :
     * struct llama_sampler *llama_sampler_init_top_p(float p, size_t min_keep)
     * }
     */
    public static MemorySegment llama_sampler_init_top_p(float p, long min_keep) {
        var mh$ = llama_sampler_init_top_p.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_sampler_init_top_p", p, min_keep);
            }
            return (MemorySegment)mh$.invokeExact(p, min_keep);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_sampler_init_min_p {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            llama_h.C_POINTER,
            llama_h.C_FLOAT,
            llama_h.C_LONG
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_sampler_init_min_p");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * struct llama_sampler *llama_sampler_init_min_p(float p, size_t min_keep)
     * }
     */
    public static FunctionDescriptor llama_sampler_init_min_p$descriptor() {
        return llama_sampler_init_min_p.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * struct llama_sampler *llama_sampler_init_min_p(float p, size_t min_keep)
     * }
     */
    public static MethodHandle llama_sampler_init_min_p$handle() {
        return llama_sampler_init_min_p.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * struct llama_sampler *llama_sampler_init_min_p(float p, size_t min_keep)
     * }
     */
    public static MemorySegment llama_sampler_init_min_p$address() {
        return llama_sampler_init_min_p.ADDR;
    }

    /**
     * {@snippet lang=c :
     * struct llama_sampler *llama_sampler_init_min_p(float p, size_t min_keep)
     * }
     */
    public static MemorySegment llama_sampler_init_min_p(float p, long min_keep) {
        var mh$ = llama_sampler_init_min_p.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_sampler_init_min_p", p, min_keep);
            }
            return (MemorySegment)mh$.invokeExact(p, min_keep);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_sampler_init_temp {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            llama_h.C_POINTER,
            llama_h.C_FLOAT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_sampler_init_temp");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * struct llama_sampler *llama_sampler_init_temp(float t)
     * }
     */
    public static FunctionDescriptor llama_sampler_init_temp$descriptor() {
        return llama_sampler_init_temp.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * struct llama_sampler *llama_sampler_init_temp(float t)
     * }
     */
    public static MethodHandle llama_sampler_init_temp$handle() {
        return llama_sampler_init_temp.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * struct llama_sampler *llama_sampler_init_temp(float t)
     * }
     */
    public static MemorySegment llama_sampler_init_temp$address() {
        return llama_sampler_init_temp.ADDR;
    }

    /**
     * {@snippet lang=c :
     * struct llama_sampler *llama_sampler_init_temp(float t)
     * }
     */
    public static MemorySegment llama_sampler_init_temp(float t) {
        var mh$ = llama_sampler_init_temp.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_sampler_init_temp", t);
            }
            return (MemorySegment)mh$.invokeExact(t);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class llama_sampler_sample {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            llama_h.C_INT,
            llama_h.C_POINTER,
            llama_h.C_POINTER,
            llama_h.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("llama_sampler_sample");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * llama_token llama_sampler_sample(struct llama_sampler *smpl, struct llama_context *ctx, int32_t idx)
     * }
     */
    public static FunctionDescriptor llama_sampler_sample$descriptor() {
        return llama_sampler_sample.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * llama_token llama_sampler_sample(struct llama_sampler *smpl, struct llama_context *ctx, int32_t idx)
     * }
     */
    public static MethodHandle llama_sampler_sample$handle() {
        return llama_sampler_sample.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * llama_token llama_sampler_sample(struct llama_sampler *smpl, struct llama_context *ctx, int32_t idx)
     * }
     */
    public static MemorySegment llama_sampler_sample$address() {
        return llama_sampler_sample.ADDR;
    }

    /**
     * {@snippet lang=c :
     * llama_token llama_sampler_sample(struct llama_sampler *smpl, struct llama_context *ctx, int32_t idx)
     * }
     */
    public static int llama_sampler_sample(MemorySegment smpl, MemorySegment ctx, int idx) {
        var mh$ = llama_sampler_sample.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("llama_sampler_sample", smpl, ctx, idx);
            }
            return (int)mh$.invokeExact(smpl, ctx, idx);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
}

