// Generated by jextract

package lm.backend.ffm.llama_h;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct llama_token_data_array {
 *     llama_token_data *data;
 *     size_t size;
 *     int64_t selected;
 *     _Bool sorted;
 * }
 * }
 */
public class llama_token_data_array {

    llama_token_data_array() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        llama_h.C_POINTER.withName("data"),
        llama_h.C_LONG.withName("size"),
        llama_h.C_LONG_LONG.withName("selected"),
        llama_h.C_BOOL.withName("sorted"),
        MemoryLayout.paddingLayout(7)
    ).withName("llama_token_data_array");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout data$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("data"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * llama_token_data *data
     * }
     */
    public static final AddressLayout data$layout() {
        return data$LAYOUT;
    }

    private static final long data$OFFSET = $LAYOUT.byteOffset(groupElement("data"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * llama_token_data *data
     * }
     */
    public static final long data$offset() {
        return data$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * llama_token_data *data
     * }
     */
    public static MemorySegment data(MemorySegment struct) {
        return struct.get(data$LAYOUT, data$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * llama_token_data *data
     * }
     */
    public static void data(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(data$LAYOUT, data$OFFSET, fieldValue);
    }

    private static final OfLong size$LAYOUT = (OfLong)$LAYOUT.select(groupElement("size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t size
     * }
     */
    public static final OfLong size$layout() {
        return size$LAYOUT;
    }

    private static final long size$OFFSET = $LAYOUT.byteOffset(groupElement("size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t size
     * }
     */
    public static final long size$offset() {
        return size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t size
     * }
     */
    public static long size(MemorySegment struct) {
        return struct.get(size$LAYOUT, size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t size
     * }
     */
    public static void size(MemorySegment struct, long fieldValue) {
        struct.set(size$LAYOUT, size$OFFSET, fieldValue);
    }

    private static final OfLong selected$LAYOUT = (OfLong)$LAYOUT.select(groupElement("selected"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int64_t selected
     * }
     */
    public static final OfLong selected$layout() {
        return selected$LAYOUT;
    }

    private static final long selected$OFFSET = $LAYOUT.byteOffset(groupElement("selected"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int64_t selected
     * }
     */
    public static final long selected$offset() {
        return selected$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int64_t selected
     * }
     */
    public static long selected(MemorySegment struct) {
        return struct.get(selected$LAYOUT, selected$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int64_t selected
     * }
     */
    public static void selected(MemorySegment struct, long fieldValue) {
        struct.set(selected$LAYOUT, selected$OFFSET, fieldValue);
    }

    private static final OfBoolean sorted$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("sorted"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool sorted
     * }
     */
    public static final OfBoolean sorted$layout() {
        return sorted$LAYOUT;
    }

    private static final long sorted$OFFSET = $LAYOUT.byteOffset(groupElement("sorted"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool sorted
     * }
     */
    public static final long sorted$offset() {
        return sorted$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool sorted
     * }
     */
    public static boolean sorted(MemorySegment struct) {
        return struct.get(sorted$LAYOUT, sorted$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool sorted
     * }
     */
    public static void sorted(MemorySegment struct, boolean fieldValue) {
        struct.set(sorted$LAYOUT, sorted$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

